/* AUTO-GENERATED from the shop's Instagram (@thedallastintshop) — 106 posts,
   145 images, 11 local reels.
   Media lives in /public/gallery/<category>/. Regenerate rather than hand-editing. */

export type IgCategory =
  | "ceramic-coating"
  | "paint-correction"
  | "powder-coating"
  | "ppf"
  | "shop"
  | "tint"
  | "wheels"
  | "wrap";

export type IgPost = {
  /** Instagram shortcode */
  code: string;
  /** Permalink to the original post */
  url: string;
  /** ISO date the post went up */
  date: string;
  category: IgCategory;
  /** Human-readable service name */
  service: string;
  vehicle: string | null;
  /** Alt text — the shop's own caption line where it reads well */
  alt: string;
  likes: number;
  plays: number | null;
  /** Local paths under /public */
  images: string[];
  /** Local mp4 for the highest-performing reels, else null */
  video: string | null;
};

export const IG_POSTS: IgPost[] = [
  {
    code: "Db6P4CpI634",
    url: "https://www.instagram.com/reel/Db6P4CpI634/",
    date: "2026-08-11",
    category: "tint",
    service: "Window Tint",
    vehicle: "BMW",
    alt: "2025 BMW M340i looking even cleaner with a fresh Llumar Ceramic Window Tint",
    likes: 6,
    plays: 401,
    images: ["/gallery/tint/2026-08-11_bmw_tint_Db6P4CpI634.jpg"],
    video: null,
  },
  {
    code: "DWSN72VDouh",
    url: "https://www.instagram.com/reel/DWSN72VDouh/",
    date: "2026-03-24",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: "Genesis",
    alt: "Genesis GV80 getting a Fiery Orange PPF",
    likes: 34,
    plays: 1332,
    images: ["/gallery/ppf/2026-03-24_genesis_ppf_DWSN72VDouh.jpg"],
    video: null,
  },
  {
    code: "DV69rPZjtpl",
    url: "https://www.instagram.com/reel/DV69rPZjtpl/",
    date: "2026-03-15",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: null,
    alt: "Before and after the wrap",
    likes: 11,
    plays: 1359,
    images: ["/gallery/wrap/2026-03-15_car_wrap_DV69rPZjtpl.jpg"],
    video: null,
  },
  {
    code: "DVJlgI-jhGb",
    url: "https://www.instagram.com/p/DVJlgI-jhGb/",
    date: "2026-02-24",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: "Mercedes",
    alt: "All green on the Mercedes",
    likes: 11,
    plays: null,
    images: ["/gallery/ppf/2026-02-24_mercedes_ppf_DVJlgI-jhGb_1.jpg", "/gallery/ppf/2026-02-24_mercedes_ppf_DVJlgI-jhGb_2.jpg", "/gallery/ppf/2026-02-24_mercedes_ppf_DVJlgI-jhGb_3.jpg", "/gallery/ppf/2026-02-24_mercedes_ppf_DVJlgI-jhGb_4.jpg"],
    video: null,
  },
  {
    code: "DUteCUwDo6x",
    url: "https://www.instagram.com/reel/DUteCUwDo6x/",
    date: "2026-02-13",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "If you want it fixed like factory, bring it to us",
    likes: 41,
    plays: 1910,
    images: ["/gallery/shop/2026-02-13_car_shop_DUteCUwDo6x.jpg"],
    video: null,
  },
  {
    code: "DUEnTXCDqoQ",
    url: "https://www.instagram.com/p/DUEnTXCDqoQ/",
    date: "2026-01-28",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "Consistent, Quality Work",
    likes: 47,
    plays: null,
    images: ["/gallery/ppf/2026-01-28_car_ppf_DUEnTXCDqoQ_1.jpg", "/gallery/ppf/2026-01-28_car_ppf_DUEnTXCDqoQ_2.jpg", "/gallery/ppf/2026-01-28_car_ppf_DUEnTXCDqoQ_3.jpg", "/gallery/ppf/2026-01-28_car_ppf_DUEnTXCDqoQ_4.jpg", "/gallery/ppf/2026-01-28_car_ppf_DUEnTXCDqoQ_5.jpg"],
    video: null,
  },
  {
    code: "DTv-QkxDn6N",
    url: "https://www.instagram.com/p/DTv-QkxDn6N/",
    date: "2026-01-20",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: "Porsche",
    alt: "Wrapped up the Porsche, video coming soon…",
    likes: 41,
    plays: null,
    images: ["/gallery/wrap/2026-01-20_porsche_wrap_DTv-QkxDn6N_1.jpg", "/gallery/wrap/2026-01-20_porsche_wrap_DTv-QkxDn6N_2.jpg", "/gallery/wrap/2026-01-20_porsche_wrap_DTv-QkxDn6N_3.jpg"],
    video: null,
  },
  {
    code: "DTjLjQXDDN-",
    url: "https://www.instagram.com/reel/DTjLjQXDDN-/",
    date: "2026-01-15",
    category: "powder-coating",
    service: "Powder Coating",
    vehicle: "Cadillac",
    alt: "Subtle upgrade. Serious impact",
    likes: 15,
    plays: 804,
    images: ["/gallery/powder-coating/2026-01-15_cadillac_powder-coating_DTjLjQXDDN-.jpg"],
    video: null,
  },
  {
    code: "DSqHummDguc",
    url: "https://www.instagram.com/reel/DSqHummDguc/",
    date: "2025-12-24",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: "Porsche",
    alt: "This isn’t a wrap | it’s a full transformation",
    likes: 46,
    plays: 2233,
    images: ["/gallery/wrap/2025-12-24_porsche_wrap_DSqHummDguc.jpg"],
    video: "/gallery/video/2025-12-24_porsche_wrap_DSqHummDguc.mp4",
  },
  {
    code: "DRiOuabjiDc",
    url: "https://www.instagram.com/reel/DRiOuabjiDc/",
    date: "2025-11-26",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "Protect your investment",
    likes: 51,
    plays: 4224,
    images: ["/gallery/ppf/2025-11-26_car_ppf_DRiOuabjiDc.jpg"],
    video: "/gallery/video/2025-11-26_car_ppf_DRiOuabjiDc.mp4",
  },
  {
    code: "DRVRIvlDnoJ",
    url: "https://www.instagram.com/p/DRVRIvlDnoJ/",
    date: "2025-11-21",
    category: "shop",
    service: "Shop Work",
    vehicle: "Bentley",
    alt: "When you drive a Bentley, the details matter",
    likes: 12,
    plays: null,
    images: ["/gallery/shop/2025-11-21_bentley_shop_DRVRIvlDnoJ_1.jpg", "/gallery/shop/2025-11-21_bentley_shop_DRVRIvlDnoJ_2.jpg", "/gallery/shop/2025-11-21_bentley_shop_DRVRIvlDnoJ_3.jpg", "/gallery/shop/2025-11-21_bentley_shop_DRVRIvlDnoJ_4.jpg", "/gallery/shop/2025-11-21_bentley_shop_DRVRIvlDnoJ_5.jpg", "/gallery/shop/2025-11-21_bentley_shop_DRVRIvlDnoJ_6.jpg"],
    video: null,
  },
  {
    code: "DRLVR6JDMXm",
    url: "https://www.instagram.com/reel/DRLVR6JDMXm/",
    date: "2025-11-17",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: "Rolls-Royce",
    alt: "Luxury deserves protection",
    likes: 84,
    plays: 3388,
    images: ["/gallery/ppf/2025-11-17_rolls-royce_ppf_DRLVR6JDMXm.jpg"],
    video: "/gallery/video/2025-11-17_rolls-royce_ppf_DRLVR6JDMXm.mp4",
  },
  {
    code: "DQxVl0ajoC4",
    url: "https://www.instagram.com/reel/DQxVl0ajoC4/",
    date: "2025-11-07",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "Don’t believe everything you hear, protect your ride the right way",
    likes: 14,
    plays: 933,
    images: ["/gallery/ppf/2025-11-07_car_ppf_DQxVl0ajoC4.jpg"],
    video: null,
  },
  {
    code: "DQfjm7ujHDg",
    url: "https://www.instagram.com/reel/DQfjm7ujHDg/",
    date: "2025-10-31",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Most people mess this part up when getting their car tinted",
    likes: 15,
    plays: 975,
    images: ["/gallery/tint/2025-10-31_car_tint_DQfjm7ujHDg.jpg"],
    video: null,
  },
  {
    code: "DQaHWETDohl",
    url: "https://www.instagram.com/reel/DQaHWETDohl/",
    date: "2025-10-29",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "PPF isn’t just a layer of film, it’s armor for your paint",
    likes: 15,
    plays: 1198,
    images: ["/gallery/ppf/2025-10-29_car_ppf_DQaHWETDohl.jpg"],
    video: null,
  },
  {
    code: "DQVBY6qDqgY",
    url: "https://www.instagram.com/reel/DQVBY6qDqgY/",
    date: "2025-10-27",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "PPF. Tint. Wraps",
    likes: 15,
    plays: 764,
    images: ["/gallery/ppf/2025-10-27_car_ppf_DQVBY6qDqgY.jpg"],
    video: null,
  },
  {
    code: "DQDI0FLjF40",
    url: "https://www.instagram.com/reel/DQDI0FLjF40/",
    date: "2025-10-20",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: "Cadillac",
    alt: "Straight off the lot and straight to protection",
    likes: 31,
    plays: 988,
    images: ["/gallery/ppf/2025-10-20_cadillac_ppf_DQDI0FLjF40.jpg"],
    video: null,
  },
  {
    code: "DP7JvAFjode",
    url: "https://www.instagram.com/reel/DP7JvAFjode/",
    date: "2025-10-17",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: "Genesis",
    alt: "You paid for quality, now keep it that way",
    likes: 30,
    plays: 991,
    images: ["/gallery/ppf/2025-10-17_genesis_ppf_DP7JvAFjode.jpg"],
    video: null,
  },
  {
    code: "DKu38TLOB23",
    url: "https://www.instagram.com/reel/DKu38TLOB23/",
    date: "2025-06-10",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Llumar pinnacle and nxt series on this elegant beauty for superior heat protection and privacy!",
    likes: 10,
    plays: 510,
    images: ["/gallery/tint/2025-06-10_car_tint_DKu38TLOB23.jpg"],
    video: null,
  },
  {
    code: "DKsmtu3M-mI",
    url: "https://www.instagram.com/reel/DKsmtu3M-mI/",
    date: "2025-06-09",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 14,
    plays: 680,
    images: ["/gallery/shop/2025-06-09_car_shop_DKsmtu3M-mI.jpg"],
    video: null,
  },
  {
    code: "DJwlhlmJqfE",
    url: "https://www.instagram.com/reel/DJwlhlmJqfE/",
    date: "2025-05-17",
    category: "tint",
    service: "Window Tint",
    vehicle: "Hyundai",
    alt: "Sonata came in for 20% @llumarfilms rear windows and windshield tint",
    likes: 9,
    plays: 661,
    images: ["/gallery/tint/2025-05-17_hyundai_tint_DJwlhlmJqfE.jpg"],
    video: null,
  },
  {
    code: "DJt_8gpOzfd",
    url: "https://www.instagram.com/reel/DJt_8gpOzfd/",
    date: "2025-05-16",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "That’s why you come to the first time!",
    likes: 7,
    plays: 809,
    images: ["/gallery/shop/2025-05-16_car_shop_DJt_8gpOzfd.jpg"],
    video: null,
  },
  {
    code: "DJrbzzGuG_W",
    url: "https://www.instagram.com/reel/DJrbzzGuG_W/",
    date: "2025-05-15",
    category: "tint",
    service: "Window Tint",
    vehicle: "Ford",
    alt: "Quick 30 minute job on this Ford F150’s front windows",
    likes: 7,
    plays: 588,
    images: ["/gallery/tint/2025-05-15_ford_tint_DJrbzzGuG_W.jpg"],
    video: null,
  },
  {
    code: "DJo4TRoOVSB",
    url: "https://www.instagram.com/reel/DJo4TRoOVSB/",
    date: "2025-05-14",
    category: "tint",
    service: "Window Tint",
    vehicle: "Chevrolet",
    alt: "Chevy 2500 came in for the @llumarfilms treatment 5% all around and 30% front windshield",
    likes: 7,
    plays: 726,
    images: ["/gallery/tint/2025-05-14_chevrolet_tint_DJo4TRoOVSB.jpg"],
    video: null,
  },
  {
    code: "DJjyKykOs8T",
    url: "https://www.instagram.com/reel/DJjyKykOs8T/",
    date: "2025-05-12",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 17,
    plays: 812,
    images: ["/gallery/shop/2025-05-12_car_shop_DJjyKykOs8T.jpg"],
    video: null,
  },
  {
    code: "DJekNz8ubiG",
    url: "https://www.instagram.com/reel/DJekNz8ubiG/",
    date: "2025-05-10",
    category: "tint",
    service: "Window Tint",
    vehicle: "BMW",
    alt: "BMW X7 for the @llumarfilms treatment Two front windows and front windshield installed",
    likes: 8,
    plays: 597,
    images: ["/gallery/tint/2025-05-10_bmw_tint_DJekNz8ubiG.jpg"],
    video: null,
  },
  {
    code: "DJcAHTruDU9",
    url: "https://www.instagram.com/reel/DJcAHTruDU9/",
    date: "2025-05-09",
    category: "shop",
    service: "Shop Work",
    vehicle: "Corvette",
    alt: "C8 Corvette Z06 came in for a rear wing install",
    likes: 14,
    plays: 701,
    images: ["/gallery/shop/2025-05-09_corvette_shop_DJcAHTruDU9.jpg"],
    video: null,
  },
  {
    code: "DJZagovunME",
    url: "https://www.instagram.com/reel/DJZagovunME/",
    date: "2025-05-08",
    category: "tint",
    service: "Window Tint",
    vehicle: "Dodge",
    alt: "Doge Charger came in for 5% @llumarfilms ceramic tint to make the vehicle overall darker",
    likes: 20,
    plays: 981,
    images: ["/gallery/tint/2025-05-08_dodge_tint_DJZagovunME.jpg"],
    video: null,
  },
  {
    code: "DJRrYguJUeP",
    url: "https://www.instagram.com/reel/DJRrYguJUeP/",
    date: "2025-05-05",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 15,
    plays: 934,
    images: ["/gallery/shop/2025-05-05_car_shop_DJRrYguJUeP.jpg"],
    video: null,
  },
  {
    code: "DJMiegCOGkc",
    url: "https://www.instagram.com/reel/DJMiegCOGkc/",
    date: "2025-05-03",
    category: "tint",
    service: "Window Tint",
    vehicle: "Toyota",
    alt: "Toyota window tint by Dallas Tint Shop",
    likes: 9,
    plays: 716,
    images: ["/gallery/tint/2025-05-03_toyota_tint_DJMiegCOGkc.jpg"],
    video: null,
  },
  {
    code: "DJHZo8RulIw",
    url: "https://www.instagram.com/reel/DJHZo8RulIw/",
    date: "2025-05-01",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: "Ford",
    alt: "Mustang GT came in for a partial hood wrap and full roof wrap using @3mfilms",
    likes: 14,
    plays: 761,
    images: ["/gallery/wrap/2025-05-01_ford_wrap_DJHZo8RulIw.jpg"],
    video: null,
  },
  {
    code: "DI_u6TLOILU",
    url: "https://www.instagram.com/reel/DI_u6TLOILU/",
    date: "2025-04-28",
    category: "tint",
    service: "Window Tint",
    vehicle: "Audi",
    alt: "Super clean Audi Q8 came in for @llumarfilms ceramic window tint for the best heat and UV protection",
    likes: 8,
    plays: 373,
    images: ["/gallery/tint/2025-04-28_audi_tint_DI_u6TLOILU.jpg"],
    video: null,
  },
  {
    code: "DI6jTymuD31",
    url: "https://www.instagram.com/reel/DI6jTymuD31/",
    date: "2025-04-26",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "The way that PPF shines in the sun G63 came in for a full vehicle @llumarfilms Satin PPF",
    likes: 18,
    plays: 680,
    images: ["/gallery/ppf/2025-04-26_car_ppf_DI6jTymuD31.jpg"],
    video: null,
  },
  {
    code: "DI3-e5vOcNu",
    url: "https://www.instagram.com/reel/DI3-e5vOcNu/",
    date: "2025-04-25",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: null,
    alt: "Batmobile Customer came in for @3mfilms Satin Black wrap",
    likes: 45,
    plays: 1529,
    images: ["/gallery/wrap/2025-04-25_car_wrap_DI3-e5vOcNu.jpg"],
    video: null,
  },
  {
    code: "DIwwYmdv8y7",
    url: "https://www.instagram.com/p/DIwwYmdv8y7/",
    date: "2025-04-22",
    category: "shop",
    service: "Shop Work",
    vehicle: "Porsche",
    alt: "Custom Satin Gold Porsche decals installed on this 718 Cayman",
    likes: 10,
    plays: null,
    images: ["/gallery/shop/2025-04-22_porsche_shop_DIwwYmdv8y7_1.jpg", "/gallery/shop/2025-04-22_porsche_shop_DIwwYmdv8y7_2.jpg"],
    video: null,
  },
  {
    code: "DIg7_wuuxCD",
    url: "https://www.instagram.com/reel/DIg7_wuuxCD/",
    date: "2025-04-16",
    category: "tint",
    service: "Window Tint",
    vehicle: "Tesla",
    alt: "Tesla window tint by Dallas Tint Shop",
    likes: 29,
    plays: 2128,
    images: ["/gallery/tint/2025-04-16_tesla_tint_DIg7_wuuxCD.jpg"],
    video: null,
  },
  {
    code: "DIbpswCs8JS",
    url: "https://www.instagram.com/reel/DIbpswCs8JS/",
    date: "2025-04-14",
    category: "tint",
    service: "Window Tint",
    vehicle: "Mercedes",
    alt: "Mercedes window tint by Dallas Tint Shop",
    likes: 13,
    plays: 515,
    images: ["/gallery/tint/2025-04-14_mercedes_tint_DIbpswCs8JS.jpg"],
    video: null,
  },
  {
    code: "DIWvTqbuL9h",
    url: "https://www.instagram.com/reel/DIWvTqbuL9h/",
    date: "2025-04-12",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: null,
    alt: "G63 in for a fresh @3mfilms wrap on its hood",
    likes: 10,
    plays: 479,
    images: ["/gallery/wrap/2025-04-12_car_wrap_DIWvTqbuL9h.jpg"],
    video: null,
  },
  {
    code: "DIRdC0AuvBD",
    url: "https://www.instagram.com/reel/DIRdC0AuvBD/",
    date: "2025-04-10",
    category: "tint",
    service: "Window Tint",
    vehicle: "Honda",
    alt: "Honda window tint by Dallas Tint Shop",
    likes: 9,
    plays: 1060,
    images: ["/gallery/tint/2025-04-10_honda_tint_DIRdC0AuvBD.jpg"],
    video: null,
  },
  {
    code: "DIJyb37OJdc",
    url: "https://www.instagram.com/reel/DIJyb37OJdc/",
    date: "2025-04-07",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Satisfying Tint Application",
    likes: 11,
    plays: 568,
    images: ["/gallery/tint/2025-04-07_car_tint_DIJyb37OJdc.jpg"],
    video: null,
  },
  {
    code: "DIEhU8wsN1W",
    url: "https://www.instagram.com/reel/DIEhU8wsN1W/",
    date: "2025-04-05",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Work van came in for @llumarfilms premium ceramic tint on their two front windows",
    likes: 12,
    plays: 483,
    images: ["/gallery/tint/2025-04-05_car_tint_DIEhU8wsN1W.jpg"],
    video: null,
  },
  {
    code: "DICACPFOys2",
    url: "https://www.instagram.com/reel/DICACPFOys2/",
    date: "2025-04-04",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Window Tint by Dallas Tint Shop",
    likes: 9,
    plays: 441,
    images: ["/gallery/tint/2025-04-04_car_tint_DICACPFOys2.jpg"],
    video: null,
  },
  {
    code: "DH_TGo_Mya_",
    url: "https://www.instagram.com/reel/DH_TGo_Mya_/",
    date: "2025-04-03",
    category: "tint",
    service: "Window Tint",
    vehicle: "Hyundai",
    alt: "Hyundai window tint by Dallas Tint Shop",
    likes: 13,
    plays: 555,
    images: ["/gallery/tint/2025-04-03_hyundai_tint_DH_TGo_Mya_.jpg"],
    video: null,
  },
  {
    code: "DH8w2R_O5lT",
    url: "https://www.instagram.com/reel/DH8w2R_O5lT/",
    date: "2025-04-02",
    category: "tint",
    service: "Window Tint",
    vehicle: "Lexus",
    alt: "Lexus window tint by Dallas Tint Shop",
    likes: 7,
    plays: 408,
    images: ["/gallery/tint/2025-04-02_lexus_tint_DH8w2R_O5lT.jpg"],
    video: null,
  },
  {
    code: "DH6KxDyMQUJ",
    url: "https://www.instagram.com/reel/DH6KxDyMQUJ/",
    date: "2025-04-01",
    category: "tint",
    service: "Window Tint",
    vehicle: "Dodge",
    alt: "Dodge window tint by Dallas Tint Shop",
    likes: 10,
    plays: 593,
    images: ["/gallery/tint/2025-04-01_dodge_tint_DH6KxDyMQUJ.jpg"],
    video: null,
  },
  {
    code: "DHyg69dMniG",
    url: "https://www.instagram.com/reel/DHyg69dMniG/",
    date: "2025-03-29",
    category: "tint",
    service: "Window Tint",
    vehicle: "Infiniti",
    alt: "Infiniti window tint by Dallas Tint Shop",
    likes: 12,
    plays: 560,
    images: ["/gallery/tint/2025-03-29_infiniti_tint_DHyg69dMniG.jpg"],
    video: null,
  },
  {
    code: "DHv4k4ZMnZi",
    url: "https://www.instagram.com/reel/DHv4k4ZMnZi/",
    date: "2025-03-28",
    category: "tint",
    service: "Window Tint",
    vehicle: "Mercedes",
    alt: "Mercedes came in for @llumarfilms premium ceramic tint on their front windshield, front and rear windows",
    likes: 9,
    plays: 640,
    images: ["/gallery/tint/2025-03-28_mercedes_tint_DHv4k4ZMnZi.jpg"],
    video: null,
  },
  {
    code: "DHtSnIisGBb",
    url: "https://www.instagram.com/reel/DHtSnIisGBb/",
    date: "2025-03-27",
    category: "tint",
    service: "Window Tint",
    vehicle: "Mercedes",
    alt: "G63 G Wagon in for front windshield, two fronts, and rear window tint using @llumarfilms ceramic tint",
    likes: 21,
    plays: 764,
    images: ["/gallery/tint/2025-03-27_mercedes_tint_DHtSnIisGBb.jpg"],
    video: null,
  },
  {
    code: "DHqzyw2uHHu",
    url: "https://www.instagram.com/reel/DHqzyw2uHHu/",
    date: "2025-03-26",
    category: "tint",
    service: "Window Tint",
    vehicle: "Toyota",
    alt: "Supra in for @llumarfilms ceramic tint, @ceramicprousa full ceramic coating, @ wrapped with @3mfilms",
    likes: 59,
    plays: 1096,
    images: ["/gallery/tint/2025-03-26_toyota_tint_DHqzyw2uHHu.jpg"],
    video: null,
  },
  {
    code: "DHlplw0MNb-",
    url: "https://www.instagram.com/reel/DHlplw0MNb-/",
    date: "2025-03-24",
    category: "tint",
    service: "Window Tint",
    vehicle: "BMW",
    alt: "X5 in for @llumarfilms 70% windshield, 15% front windows, and 5% rear ceramic tint call us for a quote today!",
    likes: 9,
    plays: 493,
    images: ["/gallery/tint/2025-03-24_bmw_tint_DHlplw0MNb-.jpg"],
    video: null,
  },
  {
    code: "DHglfvLuldI",
    url: "https://www.instagram.com/reel/DHglfvLuldI/",
    date: "2025-03-22",
    category: "tint",
    service: "Window Tint",
    vehicle: "Ford",
    alt: "Ford F150 got @llumarfilms ceramic tint on their 2 front windows",
    likes: 12,
    plays: 553,
    images: ["/gallery/tint/2025-03-22_ford_tint_DHglfvLuldI.jpg"],
    video: null,
  },
  {
    code: "DHd4rsMsPUA",
    url: "https://www.instagram.com/reel/DHd4rsMsPUA/",
    date: "2025-03-21",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 12,
    plays: 514,
    images: ["/gallery/shop/2025-03-21_car_shop_DHd4rsMsPUA.jpg"],
    video: null,
  },
  {
    code: "DHbs7JBuOJP",
    url: "https://www.instagram.com/reel/DHbs7JBuOJP/",
    date: "2025-03-20",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "@llumarfilms ceramic tint installed on this Chrysler 300",
    likes: 8,
    plays: 443,
    images: ["/gallery/tint/2025-03-20_car_tint_DHbs7JBuOJP.jpg"],
    video: null,
  },
  {
    code: "DHYvCEWsdsA",
    url: "https://www.instagram.com/reel/DHYvCEWsdsA/",
    date: "2025-03-19",
    category: "tint",
    service: "Window Tint",
    vehicle: "Hyundai",
    alt: "Elantra in for @llumarfilms ceramic tint installed by our professionals",
    likes: 5,
    plays: 494,
    images: ["/gallery/tint/2025-03-19_hyundai_tint_DHYvCEWsdsA.jpg"],
    video: null,
  },
  {
    code: "DHWQLm1vHU5",
    url: "https://www.instagram.com/reel/DHWQLm1vHU5/",
    date: "2025-03-18",
    category: "tint",
    service: "Window Tint",
    vehicle: "GMC",
    alt: "Denali came in for @llumarfilms ceramic tint, @ceramicprousa coating, and chrome delete!",
    likes: 11,
    plays: 455,
    images: ["/gallery/tint/2025-03-18_gmc_tint_DHWQLm1vHU5.jpg"],
    video: null,
  },
  {
    code: "DHO3p4ku48v",
    url: "https://www.instagram.com/reel/DHO3p4ku48v/",
    date: "2025-03-15",
    category: "tint",
    service: "Window Tint",
    vehicle: "Hyundai",
    alt: "Elantra in for a full vehicle @llumarfilms AIR & CTX for premium tint",
    likes: 11,
    plays: 393,
    images: ["/gallery/tint/2025-03-15_hyundai_tint_DHO3p4ku48v.jpg"],
    video: null,
  },
  {
    code: "DHL6CTds3NP",
    url: "https://www.instagram.com/p/DHL6CTds3NP/",
    date: "2025-03-14",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Premium tint, and premium service trusted by many",
    likes: 14,
    plays: null,
    images: ["/gallery/tint/2025-03-14_car_tint_DHL6CTds3NP_1.jpg", "/gallery/tint/2025-03-14_car_tint_DHL6CTds3NP_2.jpg", "/gallery/tint/2025-03-14_car_tint_DHL6CTds3NP_3.jpg", "/gallery/tint/2025-03-14_car_tint_DHL6CTds3NP_4.jpg"],
    video: null,
  },
  {
    code: "DHJj_N6Oe-F",
    url: "https://www.instagram.com/reel/DHJj_N6Oe-F/",
    date: "2025-03-13",
    category: "tint",
    service: "Window Tint",
    vehicle: "Corvette",
    alt: "Big C8 rolling out after two front windows @llumarfilms CTX Series 30% tint",
    likes: 25,
    plays: 606,
    images: ["/gallery/tint/2025-03-13_corvette_tint_DHJj_N6Oe-F.jpg"],
    video: null,
  },
  {
    code: "DHGuqHEJ3Nn",
    url: "https://www.instagram.com/reel/DHGuqHEJ3Nn/",
    date: "2025-03-12",
    category: "tint",
    service: "Window Tint",
    vehicle: "Tesla",
    alt: "Tesla came in for a full vehicle including front windshield @llumarfilms premium ceramic tint",
    likes: 19,
    plays: 2377,
    images: ["/gallery/tint/2025-03-12_tesla_tint_DHGuqHEJ3Nn.jpg"],
    video: null,
  },
  {
    code: "DHEOPBFOHw6",
    url: "https://www.instagram.com/p/DHEOPBFOHw6/",
    date: "2025-03-11",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "*Job Opportunity: Full-Time Tinter at *",
    likes: 23,
    plays: null,
    images: ["/gallery/tint/2025-03-11_car_tint_DHEOPBFOHw6.jpg"],
    video: null,
  },
  {
    code: "DHENTyFOJFP",
    url: "https://www.instagram.com/reel/DHENTyFOJFP/",
    date: "2025-03-11",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "This CT6V turned out great!",
    likes: 15,
    plays: 644,
    images: ["/gallery/shop/2025-03-11_car_shop_DHENTyFOJFP.jpg"],
    video: null,
  },
  {
    code: "DG8e_UZsLE7",
    url: "https://www.instagram.com/reel/DG8e_UZsLE7/",
    date: "2025-03-08",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: null,
    alt: "How to make your SUV/Vehicle look better with a chrome delete!",
    likes: 14,
    plays: 997,
    images: ["/gallery/wrap/2025-03-08_car_wrap_DG8e_UZsLE7.jpg"],
    video: null,
  },
  {
    code: "DG6Bz7XOkne",
    url: "https://www.instagram.com/reel/DG6Bz7XOkne/",
    date: "2025-03-07",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "We scratched a customers BRAND new car",
    likes: 12,
    plays: 676,
    images: ["/gallery/shop/2025-03-07_car_shop_DG6Bz7XOkne.jpg"],
    video: null,
  },
  {
    code: "DG3qi4IunPf",
    url: "https://www.instagram.com/reel/DG3qi4IunPf/",
    date: "2025-03-06",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 23,
    plays: 3135,
    images: ["/gallery/shop/2025-03-06_car_shop_DG3qi4IunPf.jpg"],
    video: "/gallery/video/2025-03-06_car_shop_DG3qi4IunPf.mp4",
  },
  {
    code: "DG3e4auuq0Z",
    url: "https://www.instagram.com/p/DG3e4auuq0Z/",
    date: "2025-03-06",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "Get at us for superior services for tint, PPF, wraps, and more!",
    likes: 26,
    plays: null,
    images: ["/gallery/ppf/2025-03-06_car_ppf_DG3e4auuq0Z_1.jpg", "/gallery/ppf/2025-03-06_car_ppf_DG3e4auuq0Z_2.jpg", "/gallery/ppf/2025-03-06_car_ppf_DG3e4auuq0Z_3.jpg", "/gallery/ppf/2025-03-06_car_ppf_DG3e4auuq0Z_4.jpg", "/gallery/ppf/2025-03-06_car_ppf_DG3e4auuq0Z_5.jpg"],
    video: null,
  },
  {
    code: "DGwJ9tSu2bb",
    url: "https://www.instagram.com/reel/DGwJ9tSu2bb/",
    date: "2025-03-03",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 25,
    plays: 824,
    images: ["/gallery/shop/2025-03-03_car_shop_DGwJ9tSu2bb.jpg"],
    video: null,
  },
  {
    code: "DGqtJNEOl3f",
    url: "https://www.instagram.com/reel/DGqtJNEOl3f/",
    date: "2025-03-01",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "X4 came in for two front windows to match the back",
    likes: 12,
    plays: 725,
    images: ["/gallery/tint/2025-03-01_car_tint_DGqtJNEOl3f.jpg"],
    video: null,
  },
  {
    code: "DGoKLO1uBq6",
    url: "https://www.instagram.com/reel/DGoKLO1uBq6/",
    date: "2025-02-28",
    category: "shop",
    service: "Shop Work",
    vehicle: "Lamborghini",
    alt: "Crazy Lamborghini Aventador transformation",
    likes: 21,
    plays: 1143,
    images: ["/gallery/shop/2025-02-28_lamborghini_shop_DGoKLO1uBq6.jpg"],
    video: null,
  },
  {
    code: "DGgRIYBue0G",
    url: "https://www.instagram.com/reel/DGgRIYBue0G/",
    date: "2025-02-25",
    category: "shop",
    service: "Shop Work",
    vehicle: "Ford",
    alt: "Can we get a deal with Ford?",
    likes: 24,
    plays: 792,
    images: ["/gallery/shop/2025-02-25_ford_shop_DGgRIYBue0G.jpg"],
    video: null,
  },
  {
    code: "DGduQZuuae1",
    url: "https://www.instagram.com/p/DGduQZuuae1/",
    date: "2025-02-24",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Protection, privacy, and pure style. Our tinted windshields do it all. Which ride would you roll with?",
    likes: 23,
    plays: null,
    images: ["/gallery/tint/2025-02-24_car_tint_DGduQZuuae1_1.jpg", "/gallery/tint/2025-02-24_car_tint_DGduQZuuae1_2.jpg", "/gallery/tint/2025-02-24_car_tint_DGduQZuuae1_3.jpg", "/gallery/tint/2025-02-24_car_tint_DGduQZuuae1_4.jpg", "/gallery/tint/2025-02-24_car_tint_DGduQZuuae1_5.jpg", "/gallery/tint/2025-02-24_car_tint_DGduQZuuae1_6.jpg", "/gallery/tint/2025-02-24_car_tint_DGduQZuuae1_7.jpg"],
    video: null,
  },
  {
    code: "DGYfSh-uxij",
    url: "https://www.instagram.com/reel/DGYfSh-uxij/",
    date: "2025-02-22",
    category: "paint-correction",
    service: "Paint Correction",
    vehicle: "BMW",
    alt: "Half and half before and after paint correction on this 1998 M3 goes crazy",
    likes: 17,
    plays: 1092,
    images: ["/gallery/paint-correction/2025-02-22_bmw_paint-correction_DGYfSh-uxij.jpg"],
    video: null,
  },
  {
    code: "DGWKUh6vTdL",
    url: "https://www.instagram.com/reel/DGWKUh6vTdL/",
    date: "2025-02-21",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "Cold Weather VS Tint and PPF!",
    likes: 15,
    plays: 1025,
    images: ["/gallery/ppf/2025-02-21_car_ppf_DGWKUh6vTdL.jpg"],
    video: null,
  },
  {
    code: "DGT7MqVuczE",
    url: "https://www.instagram.com/reel/DGT7MqVuczE/",
    date: "2025-02-20",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 99,
    plays: 3430,
    images: ["/gallery/shop/2025-02-20_car_shop_DGT7MqVuczE.jpg"],
    video: "/gallery/video/2025-02-20_car_shop_DGT7MqVuczE.mp4",
  },
  {
    code: "DGTk0jAPA8Z",
    url: "https://www.instagram.com/reel/DGTk0jAPA8Z/",
    date: "2025-02-20",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: "Lamborghini",
    alt: "Is a Lamborghini or a Ferrari easier to wrap?",
    likes: 90,
    plays: 2263,
    images: ["/gallery/wrap/2025-02-20_lamborghini_wrap_DGTk0jAPA8Z.jpg"],
    video: "/gallery/video/2025-02-20_lamborghini_wrap_DGTk0jAPA8Z.mp4",
  },
  {
    code: "DGRSZKAOQGo",
    url: "https://www.instagram.com/p/DGRSZKAOQGo/",
    date: "2025-02-19",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "for the best tint, ceramic coatings, paint corrections, wraps and PPF!",
    likes: 25,
    plays: null,
    images: ["/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_1.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_2.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_3.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_4.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_5.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_6.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_7.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_8.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_9.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_10.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_11.jpg", "/gallery/ppf/2025-02-19_car_ppf_DGRSZKAOQGo_12.jpg"],
    video: null,
  },
  {
    code: "DGEF6JJui9a",
    url: "https://www.instagram.com/reel/DGEF6JJui9a/",
    date: "2025-02-14",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "What’re the tint laws in Texas vs California?",
    likes: 40,
    plays: 1107,
    images: ["/gallery/tint/2025-02-14_car_tint_DGEF6JJui9a.jpg"],
    video: null,
  },
  {
    code: "DGBVVvru-8R",
    url: "https://www.instagram.com/reel/DGBVVvru-8R/",
    date: "2025-02-13",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "How to make your vehicle look aggressive!",
    likes: 28,
    plays: 1117,
    images: ["/gallery/shop/2025-02-13_car_shop_DGBVVvru-8R.jpg"],
    video: null,
  },
  {
    code: "DF_FR97PyxG",
    url: "https://www.instagram.com/reel/DF_FR97PyxG/",
    date: "2025-02-12",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "These are our favorite cars to work on!",
    likes: 25,
    plays: 793,
    images: ["/gallery/shop/2025-02-12_car_shop_DF_FR97PyxG.jpg"],
    video: null,
  },
  {
    code: "DF8YSU0yJX9",
    url: "https://www.instagram.com/reel/DF8YSU0yJX9/",
    date: "2025-02-11",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: null,
    alt: "Colored PPF or Vinyl Wrap?",
    likes: 19,
    plays: 904,
    images: ["/gallery/wrap/2025-02-11_car_wrap_DF8YSU0yJX9.jpg"],
    video: null,
  },
  {
    code: "DF5j75TOeIs",
    url: "https://www.instagram.com/reel/DF5j75TOeIs/",
    date: "2025-02-10",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "This is the WORST way to change your Super Cars appearance! ‍",
    likes: 55,
    plays: 2482,
    images: ["/gallery/shop/2025-02-10_car_shop_DF5j75TOeIs.jpg"],
    video: null,
  },
  {
    code: "DF0qlDXu5Mm",
    url: "https://www.instagram.com/reel/DF0qlDXu5Mm/",
    date: "2025-02-08",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "We do it all; Best Tint for a Jewelry Store!",
    likes: 38,
    plays: 1778,
    images: ["/gallery/tint/2025-02-08_car_tint_DF0qlDXu5Mm.jpg"],
    video: null,
  },
  {
    code: "DFyDGFPORYx",
    url: "https://www.instagram.com/reel/DFyDGFPORYx/",
    date: "2025-02-07",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Is hand cutting or plotted cuts easier for window tinting?",
    likes: 21,
    plays: 559,
    images: ["/gallery/tint/2025-02-07_car_tint_DFyDGFPORYx.jpg"],
    video: null,
  },
  {
    code: "DFvXGgxufSI",
    url: "https://www.instagram.com/reel/DFvXGgxufSI/",
    date: "2025-02-06",
    category: "tint",
    service: "Window Tint",
    vehicle: "Volkswagen",
    alt: "How much to tint a Volkswagen Beetle?",
    likes: 70,
    plays: 3284,
    images: ["/gallery/tint/2025-02-06_volkswagen_tint_DFvXGgxufSI.jpg"],
    video: "/gallery/video/2025-02-06_volkswagen_tint_DFvXGgxufSI.mp4",
  },
  {
    code: "DFs0AWdS1b-",
    url: "https://www.instagram.com/reel/DFs0AWdS1b-/",
    date: "2025-02-05",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "What’s the most expensive autocare products?",
    likes: 18,
    plays: 566,
    images: ["/gallery/shop/2025-02-05_car_shop_DFs0AWdS1b-.jpg"],
    video: null,
  },
  {
    code: "DFqdkirv8Bz",
    url: "https://www.instagram.com/reel/DFqdkirv8Bz/",
    date: "2025-02-04",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "What does everyone does wrong when paint correcting?",
    likes: 18,
    plays: 656,
    images: ["/gallery/shop/2025-02-04_car_shop_DFqdkirv8Bz.jpg"],
    video: null,
  },
  {
    code: "DFf1QvjOJGt",
    url: "https://www.instagram.com/reel/DFf1QvjOJGt/",
    date: "2025-01-31",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Do you need to repaint a panel after a scratch?",
    likes: 16,
    plays: 497,
    images: ["/gallery/shop/2025-01-31_car_shop_DFf1QvjOJGt.jpg"],
    video: null,
  },
  {
    code: "DFdR83Hu5aE",
    url: "https://www.instagram.com/reel/DFdR83Hu5aE/",
    date: "2025-01-30",
    category: "shop",
    service: "Shop Work",
    vehicle: "McLaren",
    alt: "How much to coat a McLaren 720S?",
    likes: 30,
    plays: 948,
    images: ["/gallery/shop/2025-01-30_mclaren_shop_DFdR83Hu5aE.jpg"],
    video: null,
  },
  {
    code: "DFawtSROfAo",
    url: "https://www.instagram.com/reel/DFawtSROfAo/",
    date: "2025-01-29",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "Why do you need ceramic tint and coating?",
    likes: 25,
    plays: 714,
    images: ["/gallery/tint/2025-01-29_car_tint_DFawtSROfAo.jpg"],
    video: null,
  },
  {
    code: "DFYcsCavEk5",
    url: "https://www.instagram.com/reel/DFYcsCavEk5/",
    date: "2025-01-28",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: null,
    alt: "Here’s the basic steps to wrapping a vehicle!",
    likes: 39,
    plays: 1076,
    images: ["/gallery/wrap/2025-01-28_car_wrap_DFYcsCavEk5.jpg"],
    video: null,
  },
  {
    code: "DFV8Nolvw9C",
    url: "https://www.instagram.com/reel/DFV8Nolvw9C/",
    date: "2025-01-27",
    category: "shop",
    service: "Shop Work",
    vehicle: "Mercedes",
    alt: "@eurochargeddallas brought this Mercedes to the right shop for a decal install",
    likes: 82,
    plays: 2579,
    images: ["/gallery/shop/2025-01-27_mercedes_shop_DFV8Nolvw9C.jpg"],
    video: null,
  },
  {
    code: "DFIsElDOOni",
    url: "https://www.instagram.com/reel/DFIsElDOOni/",
    date: "2025-01-22",
    category: "wheels",
    service: "Wheels",
    vehicle: null,
    alt: "If you don’t want your wheels dirty, do this! @ceramicprousa",
    likes: 41,
    plays: 2178,
    images: ["/gallery/wheels/2025-01-22_car_wheels_DFIsElDOOni.jpg"],
    video: null,
  },
  {
    code: "DFGGM5IuZkZ",
    url: "https://www.instagram.com/reel/DFGGM5IuZkZ/",
    date: "2025-01-21",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Can we save this customers door?",
    likes: 59,
    plays: 3322,
    images: ["/gallery/shop/2025-01-21_car_shop_DFGGM5IuZkZ.jpg"],
    video: "/gallery/video/2025-01-21_car_shop_DFGGM5IuZkZ.mp4",
  },
  {
    code: "DFDxbgqP-Em",
    url: "https://www.instagram.com/reel/DFDxbgqP-Em/",
    date: "2025-01-20",
    category: "shop",
    service: "Shop Work",
    vehicle: "Cadillac",
    alt: "Black Escalade in for a detail",
    likes: 33,
    plays: 2447,
    images: ["/gallery/shop/2025-01-20_cadillac_shop_DFDxbgqP-Em.jpg"],
    video: null,
  },
  {
    code: "DE8K7DRvtog",
    url: "https://www.instagram.com/reel/DE8K7DRvtog/",
    date: "2025-01-17",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "We make sure you guys are satisfied with our work, no matter what it is",
    likes: 31,
    plays: 1222,
    images: ["/gallery/shop/2025-01-17_car_shop_DE8K7DRvtog.jpg"],
    video: null,
  },
  {
    code: "DE5nw9FvnRM",
    url: "https://www.instagram.com/reel/DE5nw9FvnRM/",
    date: "2025-01-16",
    category: "ceramic-coating",
    service: "Ceramic Coating",
    vehicle: null,
    alt: "Ceramic Coating by Dallas Tint Shop",
    likes: 19,
    plays: 1002,
    images: ["/gallery/ceramic-coating/2025-01-16_car_ceramic-coating_DE5nw9FvnRM.jpg"],
    video: null,
  },
  {
    code: "DE3YJtJSEXP",
    url: "https://www.instagram.com/reel/DE3YJtJSEXP/",
    date: "2025-01-15",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "This is how we ensure the most accurate badge placement on your PPFed vehicle!",
    likes: 54,
    plays: 3091,
    images: ["/gallery/shop/2025-01-15_car_shop_DE3YJtJSEXP.jpg"],
    video: "/gallery/video/2025-01-15_car_shop_DE3YJtJSEXP.mp4",
  },
  {
    code: "DE0czARPFXo",
    url: "https://www.instagram.com/reel/DE0czARPFXo/",
    date: "2025-01-14",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Check out Moes way of paint correcting",
    likes: 45,
    plays: 2241,
    images: ["/gallery/shop/2025-01-14_car_shop_DE0czARPFXo.jpg"],
    video: null,
  },
  {
    code: "DEx7B4wPuDV",
    url: "https://www.instagram.com/reel/DEx7B4wPuDV/",
    date: "2025-01-13",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: null,
    alt: "My turn M8 in for a full vehicle wrap",
    likes: 36,
    plays: 1391,
    images: ["/gallery/wrap/2025-01-13_car_wrap_DEx7B4wPuDV.jpg"],
    video: null,
  },
  {
    code: "DExgxQjOMFE",
    url: "https://www.instagram.com/reel/DExgxQjOMFE/",
    date: "2025-01-13",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "Scratching a $250K car So BASICALLY you need PPF",
    likes: 66,
    plays: 4215,
    images: ["/gallery/ppf/2025-01-13_car_ppf_DExgxQjOMFE.jpg"],
    video: "/gallery/video/2025-01-13_car_ppf_DExgxQjOMFE.mp4",
  },
  {
    code: "DElDGY-POUY",
    url: "https://www.instagram.com/reel/DElDGY-POUY/",
    date: "2025-01-08",
    category: "tint",
    service: "Window Tint",
    vehicle: null,
    alt: "We tint, and we don’t judge ‍",
    likes: 50,
    plays: 2678,
    images: ["/gallery/tint/2025-01-08_car_tint_DElDGY-POUY.jpg"],
    video: "/gallery/video/2025-01-08_car_tint_DElDGY-POUY.mp4",
  },
  {
    code: "DEiho97PDBy",
    url: "https://www.instagram.com/reel/DEiho97PDBy/",
    date: "2025-01-07",
    category: "ppf",
    service: "Paint Protection Film",
    vehicle: null,
    alt: "Judah knows best what each car needs, whether it be PPF, tint, or more!",
    likes: 28,
    plays: 1046,
    images: ["/gallery/ppf/2025-01-07_car_ppf_DEiho97PDBy.jpg"],
    video: null,
  },
  {
    code: "DEaug3fvIZ-",
    url: "https://www.instagram.com/reel/DEaug3fvIZ-/",
    date: "2025-01-04",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 15,
    plays: 1141,
    images: ["/gallery/shop/2025-01-04_car_shop_DEaug3fvIZ-.jpg"],
    video: null,
  },
  {
    code: "DEYLoqivZii",
    url: "https://www.instagram.com/reel/DEYLoqivZii/",
    date: "2025-01-03",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "We take care of business here at",
    likes: 23,
    plays: 1312,
    images: ["/gallery/shop/2025-01-03_car_shop_DEYLoqivZii.jpg"],
    video: null,
  },
  {
    code: "DEVmaA_v91u",
    url: "https://www.instagram.com/reel/DEVmaA_v91u/",
    date: "2025-01-02",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "First customer in at ! Come check us out",
    likes: 37,
    plays: 2134,
    images: ["/gallery/shop/2025-01-02_car_shop_DEVmaA_v91u.jpg"],
    video: null,
  },
  {
    code: "DEGNSyGvZJ-",
    url: "https://www.instagram.com/reel/DEGNSyGvZJ-/",
    date: "2024-12-27",
    category: "shop",
    service: "Shop Work",
    vehicle: null,
    alt: "Work in progress at Dallas Tint Shop",
    likes: 19,
    plays: 894,
    images: ["/gallery/shop/2024-12-27_car_shop_DEGNSyGvZJ-.jpg"],
    video: null,
  },
  {
    code: "DDfhkXUOrmE",
    url: "https://www.instagram.com/reel/DDfhkXUOrmE/",
    date: "2024-12-12",
    category: "wrap",
    service: "Vinyl Wrap",
    vehicle: "Ford",
    alt: "Ford Shelby Mustang in for a soon to be revealed wrap",
    likes: 13,
    plays: 758,
    images: ["/gallery/wrap/2024-12-12_ford_wrap_DDfhkXUOrmE.jpg"],
    video: null,
  },
];

/** Reels we mirrored locally, most-watched first. */
export const FEATURED_REELS: IgPost[] = IG_POSTS.filter((p) => p.video).sort(
  (a, b) => (b.plays ?? 0) - (a.plays ?? 0)
);

/** Most-engaged posts overall — used for the Instagram strip. */
export const TOP_POSTS: IgPost[] = [...IG_POSTS].sort(
  (a, b) => (b.plays ?? 0) + b.likes * 20 - ((a.plays ?? 0) + a.likes * 20)
);

export function postsByCategory(category: IgCategory): IgPost[] {
  return IG_POSTS.filter((p) => p.category === category);
}
